Apps/home/urls.py
from django.urls import path
from .views import HomeView, login_view
from django.contrib.auth.views import LogoutView

app_name = 'home'
urlpatterns = [

    path('', HomeView.as_view(), name='homeapp'), 

    path('login/', login_view, name='login'), 

    path('logout/', LogoutView.as_view(), name='logout'),
]

Apps/pedidos/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import DireccionListView, DireccionCreateView, DireccionUpdateView, dir_eliminar
from .views import PedidoListView, PedidoCreateView, obtener_precio_producto, PedidoDetailView, PedidoUpdateView, pedido_eliminar


app_name='pedidos'
urlpatterns = [


#URLS DIRECCION
    path('direcciones/', DireccionListView.as_view(), name='listadirecciones'),
    path('direcciones/crear/', DireccionCreateView.as_view(), name='creardirecciones'),
    path('direcciones/editar/<int:pk>/', DireccionUpdateView.as_view(), name='editardirecciones'), 
     path('direcciones/<int:pk>/eliminar/', dir_eliminar, name='dir_eliminar'),
    

#URLS DE PEDIDO
    path('', PedidoListView.as_view(), name='pedido_list'),
    path('crear/', PedidoCreateView.as_view(), name='crearpedido'),
    path('ajax/obtener_precio/', obtener_precio_producto, name='obtener_precio_producto'),
    path('<int:pk>/', PedidoDetailView.as_view(), name='pedido_detail'),
    path('<int:pk>/editar/', PedidoUpdateView.as_view(), name='pedido_update'),
    path('<int:pk>/eliminar/', pedido_eliminar, name='pedido_eliminar'), 

]

Apps/productos/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ProductoListView, ProductoCreateView, ProductoUpdateView, producto_eliminar, ProductoDetailView
from .views import CategoriaListView, CategoriaCreateView, CategoriaUpdateView, categoria_eliminar

app_name='productos'
urlpatterns = [
#URLS PRODUCTOS
    path('', ProductoListView.as_view(), name='listaproductos'),
    path('crear', ProductoCreateView.as_view(), name='crearproductos'),
    path('editar/<int:pk>', ProductoUpdateView.as_view(), name='editarproducto'),
    path('<int:pk>/eliminar/', producto_eliminar, name='producto_eliminar'),
    path('<int:pk>/', ProductoDetailView.as_view(), name='producto_detail'),

    #URLS PARA CATEGORIA
    path('categoria/', CategoriaListView.as_view(), name='listacategoria'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='crearcategoria'),
    path('categoria/editar/ <int:pk>', CategoriaUpdateView.as_view(), name='editarcategoria'),
    path('categoria/<int:pk>/eliminar/', categoria_eliminar, name='categoria_eliminar'),
]

Apps/reportes/urls.py
from django.urls import path
from .views import DashboardReportesView, generar_reporte

app_name = 'reportes_app'

urlpatterns = [

    path('dashboard/', DashboardReportesView.as_view(), name='dashboard'),
    path('dashboard/generar/', generar_reporte, name='generar_reporte'),

]

Apps/usuarios/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UsuarioListView , UsuarioCreateView, UsuarioUpdateView, usuario_eliminar, UsuarioDetailView
from .views import RoleListView , RoleCreateView, RoleUpdateView, rol_eliminar

app_name='usuarios'
urlpatterns = [
    #PATHS PARA USUARIOS
    path('', UsuarioListView.as_view(), name='listausuarios'),
    path('crear/', UsuarioCreateView.as_view(), name='crearusuario'),
    path('editar/ <int:pk>', UsuarioUpdateView.as_view(), name='editarusuario'),
    path('<int:pk>/eliminar/', usuario_eliminar, name='usuario_eliminar'),
    path('<int:pk>/', UsuarioDetailView.as_view(), name='usuario_detail'),

    #PATHS PARA ROLES
    path('roles/', RoleListView.as_view(), name='listaroles'),
    path('roles/crear/', RoleCreateView.as_view(), name='crearrol'),
    path('roles/editar/<int:pk>/', RoleUpdateView.as_view(), name='editarrol'),
    path('roles/<int:pk>/eliminar/', rol_eliminar, name='rol_eliminar'),

]

PFDESARROLLO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Apps.home.urls')), 

    path('usuarios/', include('Apps.usuarios.urls', namespace='usuarios')),
    path('productos/', include('Apps.productos.urls', namespace='productos')),
    path('pedidos/', include('Apps.pedidos.urls', namespace='pedidos')),
    path('reportes/', include('Apps.reportes.urls', namespace='reportes')),
]

Apps/home/models.py
from django.db import models

# Create your models here.

Apps/home/forms.py
from django import forms

class LoginForm(forms.Form):
    nombre_u = forms.CharField(
        max_length=100, 
        label='Nombre de Usuario',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label='Contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

Apps/home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout 
from .forms import LoginForm 
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'


def login_view(request):
    if request.user.is_authenticated:
        return redirect('home:homeapp') 
        
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            nombre_u = form.cleaned_data['nombre_u']
            password = form.cleaned_data['password']
            

            user = authenticate(request, username=nombre_u, password=password) 
            
            if user is not None:

                if user.is_active:
                    login(request, user) 
                    messages.success(request, f'Bienvenido, {user.nombre_p or user.nombre_u}!') 
    
                    next_url = request.GET.get('next', 'home:homeapp') 
                    return redirect(next_url) 
                else:
                    messages.error(request, 'Su cuenta está inactiva.')
            else:
                messages.error(request, 'Nombre de usuario o contraseña incorrectos.')
    else:
        form = LoginForm()
        
    context = {'form': form}
    return render(request, 'login.html', context)

Apps/home/templates/baselogin.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Iniciar Sesión - PAGINA CAFETERIA{% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="author" content="">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&family=Open+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <style>
        body {
            background-image: url('{% static "images/fondo_login.jpg" %}');
            background-size: cover; 
            background-position: center; 
            background-repeat: no-repeat; 
        }

        .logo-container {
            position: relative;
            text-align: center; 
            z-index: 10; 
        }

        .logo-background {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: rgba(255, 255, 255, 0.6); 
            z-index: 5; /* Detrás del logo */
            border-radius: 10px;
        }

        .logo-container img {
            max-width: 100%; 
            height: auto;
            filter: drop-shadow(2px 2px 4px rgba(0, 0, 0, 0.5)); /* Sombra para el logo */
        }

        header {
    background-color: rgba(255, 255, 255, 0.9); /* Fondo blanco semitransparente para el header */
    padding: 10px 0; /* Ajusta el padding según sea necesario */
    z-index: 10; /* Asegura que el header esté por encima */
}

body {
    background-image: url('{% static "images/fondo_login.jpg" %}');
    background-size: cover; 
    background-position: center; 
    background-repeat: no-repeat; 
}
    </style>
</head>
<body class="login-background">

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <defs>
            <symbol xmlns="http://www.w3.org/2000/svg" id="link" viewBox="0 0 24 24">...</symbol>
            <symbol xmlns="http://www.w3.org/2000/svg" id="arrow-right" viewBox="0 0 24 24">...</symbol>
            <symbol xmlns="http://www.w3.org/2000/svg" id="close" viewBox="0 0 15 15">...</symbol>
        </defs>
    </svg>

    <div class="preloader-wrapper">...</div> 
    <header>
        <div class="container-fluid">
            <div class="row py-3 border-bottom">
                <div class="col-sm-4 col-lg-3 text-center text-sm-start">
                    <div class="logo-container">
                        <div ></div> 
                        <a href="{% url 'home:login' %}">
                            <img src="{% static 'images/logo.png' %}" alt="logo" class="img-fluid">
                        </a>
                    </div>
                </div>
                <div class="col-sm-6 offset-sm-2 offset-md-0 col-lg-5 d-none d-lg-block">
                </div>
                <div class="col-sm-8 col-lg-4 d-flex justify-content-end gap-5 align-items-center mt-4 mt-sm-0 justify-content-center justify-content-sm-end">
                    <div class="support-box text-end d-none d-xl-block">
                        <span class="fs-6 text-muted">Soporte ↓</span>
                        <h5 class="mb-0">+502 58217572</h5>
                    </div>
                </div>
            </div>
        </div>
        
    </header>
    
    {% block contenido %}
    {% endblock %}

    <footer class="py-5">
      </footer>
    <div id="footer-bottom">
      </div>
    
    <script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

Apps/home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}

<section class="py-5 background-pattern bg-info"> 
    <div class="container">
        
        <h2 class="text-center mb-5">Módulos del sistema</h2>

        <div class="row justify-content-center text-center">
            
            <div class="col-6 col-md-3 mb-4">
                <a href="{% url 'usuarios:listausuarios' %}" class="d-block text-decoration-none p-4 rounded-3 shadow-lg bg-white h-100">
                    <img src="{% static 'images/icono_usuario.png' %}" alt="Módulo Usuarios" class="img-fluid mb-3" style="max-width: 80px;">
                    <h5 class="mt-2 text-dark">USUARIOS</h5>
                </a>
            </div>

            <div class="col-6 col-md-3 mb-4">
                <a href="{% url 'usuarios:listaroles' %}" class="d-block text-decoration-none p-4 rounded-3 shadow-lg bg-white h-100">
                    <img src="{% static 'images/icono_roles.png' %}" alt="Módulo Roles" class="img-fluid mb-3" style="max-width: 80px;">
                    <h5 class="mt-2 text-dark">ROLES</h5>
                </a>
            </div>

            <div class="col-6 col-md-3 mb-4">
                <a href="{% url 'productos:listaproductos' %}" class="d-block text-decoration-none p-4 rounded-3 shadow-lg bg-white h-100">
                    <img src="{% static 'images/icono_menu.png' %}" alt="Módulo Productos" class="img-fluid mb-3" style="max-width: 80px;">
                    <h5 class="mt-2 text-dark">PRODUCTOS</h5>
                </a>
            </div>

            <div class="col-6 col-md-3 mb-4">
                <a href="{% url 'pedidos:pedido_list' %}" class="d-block text-decoration-none p-4 rounded-3 shadow-lg bg-white h-100">
                    <img src="{% static 'images/icono_pedidos.png' %}" alt="Módulo Pedidos" class="img-fluid mb-3" style="max-width: 80px;">
                    <h5 class="mt-2 text-dark">PEDIDOS</h5>
                </a>
            </div>

            <div class="col-6 col-md-3 mb-4">
                <a href="{% url 'reportes:dashboard' %}" class="d-block text-decoration-none p-4 rounded-3 shadow-lg bg-white h-100">
                    <img src="{% static 'images/icono_reportes.png' %}" alt="Módulo Reportes" class="img-fluid mb-3" style="max-width: 80px;">
                    <h5 class="mt-2 text-dark">Reportes</h5>
                </a>
            </div>
            
        </div>

        <hr class="my-5">

        
        {% if user.is_authenticated %}
            <p class="text-center">
                ¡Bienvenido de nuevo, 
                <strong>{{ user.nombre_p|default:user.nombre_u }}</strong>!
            </p>

            <div class="text-center mt-4">
                <form method="post" action="{% url 'home:logout' %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger">Cerrar Sesión</button>
                </form>
            </div>
            
        {% else %}
            <p class="text-center">No has iniciado sesión.</p>
        {% endif %}

    </div>
</section>

{% endblock contenido %}

Apps/home/templates/login.html
{% extends "baselogin.html" %} 

{% block title %}Iniciar Sesión{% endblock %}

{% block contenido %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-lg">
                    <div class="card-header bg-dark text-white text-center">
                        <h3>Acceso al Sistema</h3>
                    </div>
                    <div class="card-body">
                        
                        {# Muestra mensajes de éxito/error/info si existen (ej: contraseña incorrecta) #}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                        
                        {# El formulario POST apunta a la URL de login actual #}
                        <form method="post">
                            {% csrf_token %}
                            
                            {# Campo de Nombre de Usuario (nombre_u) #}
                            <div class="mb-3">
                                {{ form.nombre_u.label_tag }}
                                {{ form.nombre_u }}
                            </div>
                            
                            {# Campo de Contraseña (password) #}
                            <div class="mb-3">
                                {{ form.password.label_tag }}
                                {{ form.password }}
                            </div>
                            
                            <div class="d-grid gap-2 mt-4">
                                <button type="submit" class="btn btn-success">INICIAR SESIÓN</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}